name: static website hosting

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@4.1.1

    - name: setting up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{secrets.ACCESS_KEY}}
        aws-secret-key-id: ${{secrets.SECRET_KEY}}
    
    - name: copying the code to S3 bucket
      run: aws s3 sync . s3://static-file-hosting-github-actions --delete
